
version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: aitools
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    # command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    command: >
      python -m debugpy --listen 0.0.0.0:5678 --wait-for-client manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"   # Django 开发端口
      - "5678:5678"   # Debugpy 调试端口
    depends_on:
      - db
    environment:
      DEBUG: "True"
      DB_NAME: aitools
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5433
      DJANGO_SETTINGS_MODULE: core.settings

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  postgres_data:
